### PR TITLE
Remove AT dependency and PY3 compatibility

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by agitator** [comment]
@tomgross could you update the description "Data validation package for Archetypes." in  Readme.txt?

**Comment by gforcada** [comment]
@tomgross out of curiosity, I see that the [reverse dependencies](http://jenkins.plone.org/py3/deps-reverse/Products.validation.svg) of this package are only AT related ones, so what's the idea of removing it? Are you using it outside AT as well? As soon as this gets merged, would you mind adding this package on https://github.com/plone/buildout.coredev/blob/5.1/experimental/py3x-test.cfg you can try then to run http://jenkins.plone.org/view/py3/job/py3-test/ and see if the tests are picked up.

Thanks for your efforts towards Plone on Python 3!! 🙇

**Comment by tomgross** [comment]
@gforcada As the tests show: There is nothing AT specific on this package. It could be used everywhere. It is used for collective.easyform and we indeed use it to put other custom validators on top of the base validators found in the package.

**Comment by mauritsvanrees** [comment]
Thanks! 👍 

I am inclined to create a branch 2.0.x without these changes and let Plone coredev 4.3 use that, to avoid accidental errors due to changes that do not benefit anyone on 4.3. Would you agree?

**Pull request merged**
